name: Deploy on Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release tag name
        id: get-latest-release
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const release = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return release.data.tag_name;

      - name: Use latest release tag name
        run: |
          echo "Latest release tag is ${{ steps.get-latest-release.outputs.result }}"
          # You can use ${{ steps.get-latest-release.outputs.result }} as needed

      - name: Login to Local Docker Registry
        run: docker login -u ${{ secrets.LOCAL_REGISTRY_USERNAME }} -p ${{ secrets.LOCAL_REGISTRY_PASSWORD }} ${{ secrets.LOCAL_REGISTRY_URL }}

      - name: Push Docker image
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.LOCAL_REGISTRY_URL }}/${{ secrets.DOCKER_IMAGE }}:${{ steps.get-latest-release.outputs.result }} -f .github/workflows/Dockerfile . --push

      - name: Notify Deployment
        run: echo "Deployment of version ${{ steps.get-latest-release.outputs.result }} to local registry completed."
